# Generated by Django 2.0.dev20170509185503 on 2017-06-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('alternativa1', models.CharField(max_length=1)),
                ('alternativa2', models.CharField(max_length=1)),
                ('alternativa3', models.CharField(max_length=1)),
                ('alternativa4', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='alternativa',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Pregunta'),
        ),
    ]
