# Generated by Django 2.0.dev20170509185503 on 2017-06-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(default='Sin Dominio', max_length=255, verbose_name='domain')),
                ('url', models.URLField(max_length=1000, verbose_name='url')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name_plural': 'Materiales Web',
                'verbose_name': 'Material Web',
            },
        ),
    ]
