# Generated by Django 2.0.dev20170509185503 on 2017-06-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialWeb',
            new_name='MaterialWebBruto',
        ),
        migrations.AlterModelOptions(
            name='materialwebbruto',
            options={'verbose_name': 'Material Web Rescatado', 'verbose_name_plural': 'Materiales Web Rescatados'},
        ),
    ]
