# Generated by Django 2.0.dev20170509185503 on 2017-06-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0002_auto_20170606_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialWebBruto',
        ),
    ]
