# Generated by Django 2.0.dev20170509185503 on 2017-06-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialWebProcesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.URLField(default='Sin Dominio', max_length=255, verbose_name='dominio')),
                ('url', models.URLField(max_length=1000, verbose_name='url')),
                ('titulo', models.CharField(max_length=255, verbose_name='titulo')),
                ('idioma', models.CharField(max_length=10, verbose_name='idioma')),
                ('tipo_aprendizaje', models.CharField(max_length=10, verbose_name='tipo_aprendizaje')),
                ('contenido', models.TextField(verbose_name='contenido')),
            ],
            options={
                'verbose_name_plural': 'Materiales Web Procesados',
                'verbose_name': 'Material Web Procesado',
            },
        ),
    ]
