# Generated by Django 2.0.dev20170509185503 on 2017-06-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialwebprocesado',
            name='codigo_fuente',
            field=models.TextField(default='', verbose_name='codigo_fuente'),
            preserve_default=False,
        ),
    ]
